#!/bin/bash

dir="${1:-.}"

find "$dir" -type f \( -name "*.c" -o -name "*.js" -o -name "*.py" \) | while read -r f; do
	first=$(head -n 1 "$f")
	case "$first" in
	\#*|//*|/\**)
echo "$f: есть комментарий"
;;
*)
echo "$f: нет комментария"
;;
esac
done
